# Generated by Django 5.0.3 on 2024-05-02 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('main', '0006_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.member')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_completed', models.BooleanField()),
                ('is_cash', models.BooleanField()),
                ('member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.member')),
                ('menu_items', models.ManyToManyField(to='main.menu')),
                ('way_recieved_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.way_recieved')),
            ],
        ),
    ]
