# Generated by Django 5.0.3 on 2024-05-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_member_address_remove_member_email_and_more'),
        ('checkout', '0004_alter_cartitem_user'),
    ]

    operations = [
    ]
