# Generated by Django 5.0.3 on 2024-05-03 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_merge_20240502_1041'),
        ('main', '0006_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.menu')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(to='checkout.orderline'),
        ),
    ]
