# Generated by Django 5.0.3 on 2024-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderline_alter_order_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
