# Generated by Django 5.0.3 on 2024-04-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(to='main.menu'),
        ),
    ]
